#!/usr/bin/with-contenv bash

# create folders
if [ ! -d "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}" ]; then \
mkdir -p "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}"
chown -R abc:abc /config
fi

# remove plex pid after unclean stop
[[ -f "/config/Library/Application Support/Plex Media Server/plexmediaserver.pid" ]] && \
  rm -f "/config/Library/Application Support/Plex Media Server/plexmediaserver.pid"

# function to randomly sample 50 files for their owner and only chown if not abc
chowner () {
files=(${1}/*)
for i in {1..50}; do
        user=$(stat -c '%U' $(printf "%s\n" "${files[RANDOM % ${#files[@]}]}"))
        if [ "${user}" != "abc" ]; then
                chown -R abc:abc ${1}
                break
        fi
done
}

# permissions
echo "Setting permissions"
abc_dirs=( \
/config \
)
for i in "${abc_dirs[@]}"; do
        if [ "$(ls -A ${i})" ]; then
                chowner ${i}
        else
                chown -R abc:abc ${i}
        fi
done