#!/usr/bin/with-contenv bash

XML_CONFIG="/config/Library/Application Support/Plex Media Server/Preferences.xml"

# Fallback to ALLOWED_NETWORKS value
NOAUTH_NETWORKS="${NOAUTH_NETWORKS:-$ALLOWED_NETWORKS}"

update_or_insert_attr() {
  # Usage: update_or_replace_attr <attribute> <value> <xmlpath>

  local element attribute_name attribute_value xml_path
  element="/Preferences"
  attribute_name="${1:?}"
  attribute_value="${2:?}"
  xml_path="${3:?}"

  local response
  response="$(xmlstarlet select --text --template --match "$element" --value-of "@${attribute_name}" "${xml_path}")"

  # Only write to file if the desired value differs from the current
  if [[ "$response" == "$attribute_value" ]]; then
     return
  fi

  xmlstarlet edit --inplace --insert "$element" --type attr --name "$attribute_name" --value "$attribute_value" "$xml_path"
}

ensure_xml_exists() {
  # Usage: ensure_xml_exists <xml_path>

  if [[ -e "${1:?}" ]]; then
     printf '%s\n' "File '$1' already exists. Skipping..."
     return
  fi

  local parent
  parent="$(dirname "${1:?}")"

  if [[ ! -d "$parent" ]]; then
     mkdir -p "$parent"
  fi

  printf '%s\n' "<?xml version=\"1.0\" encoding=\"utf-8\"?><Preferences/>" > "$1"

  chown -R abc:abc "$parent"
}

main() {
  ensure_xml_exists "$XML_CONFIG"

  # Comma delimited string of ip cidr blocks that should be considered local
  if [[ -n "$ALLOWED_NETWORKS" ]]; then
    update_or_insert_attr allowedNetworks "$ALLOWED_NETWORKS" "$XML_CONFIG"
  fi

  # Comma delimited string of ip cidr blocks that shouldn't require auth
  if [[ -n "$NOAUTH_NETWORKS" ]]; then
    update_or_insert_attr LanNetworksBandwidth "$NOAUTH_NETWORKS" "$XML_CONFIG"
  fi

  # Comma delimited string of https/http urls used to access server
  if [[ -n "$ADVERTISE_URLS" ]]; then
    update_or_insert_attr allowedNetworks "$ADVERTISE_URLS" "$XML_CONFIG"
  fi

  # Human readable name used to identify server on clients
  if [[ -n "$SERVER_NAME" ]]; then
    update_or_insert_attr FriendlyName "$SERVER_NAME" "$XML_CONFIG"
  fi
}

main
